### ISSUE TITLE
Support SDS in kourier

### ISSUE THREAD

**Issue by ZhuangYuZY** [knative-sandbox/net-kourier#135]
We tested kourier with knative. The result is great comparing with istio. But one blocker to adapt kourier is it is not support SDS which support by istio https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/.

My user case is for each kube namespace (e.g. test-ns), we will order a https certs for namespace domain (e.g. *.test-ns.root-domain.com), then kn service will have application domain based on it, like app1.test-ns.root-domain.com, app2.test-ns.root-domain.com. We also have other namespace like test-ns1, test-ns2 in the kube cluster.

For istio, what we are doing is ordering https cert, generate kube secret to store the cert, and update istio gateway `knative-ingress-gateway` to load the kube secret. Then istio will serve the https request for domain *.test-ns.root-domain.com.
```
- hosts:
    - '*.test-ns.root-domain.com'
    port:
      name: https-test-ns
      number: 443
      protocol: HTTPS
    tls:
      credentialName: test-ns
      mode: SIMPLE
      subjectAltNames: [] 
```

Any thinking around this, do we plan to support it in Kourier ? Thank you.
@davidor and @jmprusi ^^^ Thank you.
