### ISSUE TITLE
General purpose ingress?

### ISSUE THREAD

**Issue by mkyrilov** [knative-sandbox/net-kourier#652]
Hi there.

I was wondering if Kourier can be used with "normal" ingresses? I haven't been able to get this to work, and I can't find any config or documentation for or against this use case.

I have Knative + Kourier installed and configured as described in the [docs](https://knative.dev/docs/admin/install/), and all that works great. Then I have a simple Nginx Deployment, Service, and Ingress:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  labels:
    name: nginx
  annotations:
    "kubernetes.io/ingress.class": "kourier"
spec:
  rules:
  - host: nginx.10.111.4.115.sslip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port: 
              number: 80
```
