### ISSUE TITLE
Kourier is not compatible with Knative-Service timeoutSeconds custom value with more than 300 seconds

### ISSUE THREAD

**Issue by skycyan** [knative-sandbox/net-kourier#680]
When a long GRPC connection is established, the data does not return within 5 minutes, and the connection will be interrupted, which can be solved by adjusting the timeoutSeconds parameter. However, when kourier is used as a gateway, the timeoutSeconds value is fixed to 300 seconds by default and cannot be customized.

In use, it is found that in kourier v0.26.0 version, kourier does not support the custom parameter of timeoutSeconds in Knative-Service.

Also does not support, the max-revision-timeout-seconds and revision-timeout-seconds custom parameters in knative-serving comfigmap config-defaults.

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
    spec: 
      timeoutSeconds: 600   # kourier gw is not compatible with this custom number.
      containers:
      - image: imageurl
        imagePullPolicy: IfNotPresent
        ports:
          - name: h2c
            containerPort: 8080
```

**Reminder:** Istio gateway is compatible with timeoutSeconds custom value.
