### ISSUE TITLE
HTTP Policy/behaviour is not supported by KSVC

### ISSUE THREAD

**Issue by RamyChaabane** [knative-sandbox/net-kourier#772]
Hello

I want to change the default behaviour of HTTP traffic from "enabled" to whether "redirected" or "disabled".

According to [knative documentation  ](https://knative.dev/docs/serving/services/http-protocol/), we can do that in different ways: 
- Global by editing config-network configmap 
- Per service by adding `networking.knative.dev/http-protocol: "<option>"` annotation

Also There is an inconsistency between this doc and this [thread](https://knative.dev/docs/serving/using-auto-tls/#turn-on-auto-tls) as "disabled" option is not mentioned in the first doc

When testing with Kourier, I noticed that only Global setup is supported

Do you confirm that this is a bug?
I can open a PR if necessary 

Thank you!

**Comment by nak3** [comment]
Hi @RamyChaabane 

> Also There is an inconsistency between this doc and this thread as "disabled" option is not mentioned in the first doc

We have an on-going discussion in https://github.com/knative/networking/issues/417. If you want to have a `disable` option support, could you please comment your use-case on https://github.com/knative/networking/issues/417?

> When testing with Kourier, I noticed that only Global setup is supported

Do you mean that the annotation did not work? What values are set in the `httpOption` of Kingress? Please check it in your Kingress like:

```
$ kubectl get king -o yaml
 ...
  spec:
    httpOption: Enabled
```
Kourier does not support `disabled` but redirect option should work.

**Comment by RamyChaabane** [comment]
Hello @nak3 
Exactly! the annotation did not work, and `httpOption` equals to `Enabled` with or without annotation and I think that's why it's not working, as [here](https://github.com/knative-sandbox/net-kourier/blob/main/pkg/generator/ingress_translator.go#L181) we don't check the annotation

```
# netkubectl describe king  pproxmigddnsuxyb-toto

Name:         pproxmigddnsuxyb-toto
...
Annotations:  networking.internal.knative.dev/rollout:
                {"configurations":[{"configurationName":"pproxmigddnsuxyb-toto","percent":100,"revisions":[{"revisionName":"pproxmigddnsuxyb-toto-00002","...
              networking.knative.dev/disableAutoTLS: false
              networking.knative.dev/http-protocol: redirected
              networking.knative.dev/ingress.class: kourier.ingress.networking.knative.dev
...
Spec:
  Http Option:  Enabled
  Rules:
    Hosts:
      ...
```
