### ISSUE TITLE
Envoy ext_authz filter: `/.well-known/acme-challenge/` path is not ignored

### ISSUE THREAD

**Issue by RamyChaabane** [knative-sandbox/net-kourier#777]
Hello

when enabling both autoTLS and ext_authz filter, the path `/.well-known/acme-challenge/` for HTTP01 challenge is not ignored!
The traffic will necessarily pass throughout  the external authorization service (for no reason)

I think it would be great if we can add `typed_per_filter_config` to the route created for HTTP01 challenge in order to disable the filter in the route level as mentioned [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#per-route-configuration), for instance

```
- name: >-
   (b2eac33b-ee65-404d-a0ab-fceaa6f26210/authztlsv2f98enkds-toto).Rules[1]
  domains:
   - authztlsv2f98enkds-toto.functions.fnc.dev.fr-par.scw.cloud
   - 'authztlsv2f98enkds-toto.functions.fnc.dev.fr-par.scw.cloud:*'
  routes:
   - match:
       prefix: >-
         /.well-known/acme-challenge/G84xbCs9GO2ENE_50aUBuOzs_T12Auy1AacLKcHcQOU
       headers:
         - name: K-Network-Hash
           exact_match: override
     route:
       weighted_clusters:
         clusters:
           - name: >-
               b2eac33b-ee65-404d-a0ab-fceaa6f26210/cm-acme-http-solver-gznmm
             weight: 100
       timeout: 0s
       upgrade_configs:
         - upgrade_type: websocket
           enabled: true
     request_headers_to_add:
       - header:
           key: K-Network-Hash
           value: >-
             55eb12aadbd590cfc4eccc0dda6c0f63df4cfac7bba366aec4224fc628813f78
         append: false
     typed_per_filter_config:
       envoy.filters.http.ext_authz:
         "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
         disabled: true
```
