### ISSUE TITLE
DomainMapping: websocket protocol doesn't work

### ISSUE THREAD

**Issue by RamyChaabane** [knative-sandbox/net-kourier#801]
Hello,

I'm trying to invoke my Knative service using websocket, it works just fine when I invoke my service natively, but it doesn't work when I invoke my service through a domain mapping

After some troubleshooting, I've noticed that, when we do a domain mapping, envoy is configured in a way that the cluster is only accepting `http2` traffic, and as far as I understand, this feature is not yet supported with envoy when it comes to websocket (see this [issue](https://github.com/envoyproxy/envoy/issues/8547))

```
dynamic_active_clusters:
      - version_info: 5c2eb239-9e04-409d-b195-115341c4d77b
        cluster:
          '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
          name: b2eac33b-ee65-404d-a0ab-fceaa6f26210/websocket82e6cnkg-test
          type: LOGICAL_DNS
          connect_timeout: 5s
          load_assignment:
            cluster_name: b2eac33b-ee65-404d-a0ab-fceaa6f26210/websocket82e6cnkg-test
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: kourier-internal.kourier-system.svc.cluster.local
                          port_value: 80
                          ipv4_compat: true
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              '@type': >-
                type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options: {}
```
I undersand why it's configured that way: the k8s service that forwards the traffic to the knative service is an `ExteralName` service that uses port `80` and `http2`

```
Name:              websocket82e6cnkg-test
Namespace:         b2eac33b-ee65-404d-a0ab-fceaa6f26210
Selector:          <none>
Type:              ExternalName
IP Families:       <none>
IP:
IPs:               <none>
External Name:     kourier-internal.kourier-system.svc.cluster.local
Port:              http2  80/TCP
TargetPort:        80/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

in [this section](https://github.com/knative-sandbox/net-kourier/blob/main/pkg/generator/ingress_translator.go#L138) of the controller code, we check whether the port name is an `http2` port, and according to that, we set the value of `http2` bool variable

By disabling this value (forcing http2 to false), the websockt works

- Is there a reason why the k8s service is configured that way?
- What if we let the user choose how to configure the envoy cluster?
    - add an annotation to the king/svc to wheteher we need `http2`
    - according to this, we override the value of `http2` bool variable
