### ISSUE TITLE
Add support for readiness and liveness probes

### ISSUE THREAD

**Issue by mbrancato** [knative-sandbox/net-kourier#838]
While the Knative spec allows readiness and liveness probes on containers, these settings have unexpected results with Kourier.

env info:
Kubernetes 1.22.8 - GKE
Knative 1.4.0
Kourier 1.4.0

The expected config is my best guess - but currently the probes do not seem to point to the correct services. The services, however, work fine except enabling probes will eventually cause the containers to fail and restart. If I have totally missed the boat here, please, let me know. I couldn't find any probe examples in the kourier repo.

When enabling an http/2 service like this:
```yaml
          ports:
            - name: h2c
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
          readinessProbe:
            httpGet:
              path: /readyz
```

The resulting revision/pod has: 
```
...
Containers:
  my-app:
    Liveness:  http-get http://:80/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
  queue-proxy:
    Readiness:  http-get http://:8013/ delay=0s timeout=1s period=1s #success=1 #failure=3
...
```

Likely expected:
```
...
Containers:
  my-app:
    Liveness:  http-get http://:8013/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8013/readyz delay=0s timeout=1s period=1s #success=1 #failure=3
  queue-proxy:
    Readiness:  http-get http://:8013/readyz delay=0s timeout=1s period=1s #success=1 #failure=3
...
```

When enabling an http/1.1 / http/2 service like this:
```yaml
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
          readinessProbe:
            httpGet:
              path: /readyz
```

The resulting revision/pod has: 
```
...
Containers:
  my-app:
    Liveness:  http-get http://:80/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
  queue-proxy:
    Readiness:  http-get http://:8012/ delay=0s timeout=1s period=1s #success=1 #failure=3
...
```

Likely expected:
```
...
Containers:
  my-app:
    Liveness:  http-get http://:8012/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8012/readyz delay=0s timeout=1s period=1s #success=1 #failure=3
  queue-proxy:
    Readiness:  http-get http://:8012/readyz delay=0s timeout=1s period=1s #success=1 #failure=3
...
```
