### ISSUE TITLE
Feature Request Discussion: Enable configuring Envoy private key providers

### ISSUE THREAD

**Issue by xxinran** [knative-sandbox/net-kourier#887]
# Introduction
As an ingress gateway, Kourier need handle a large number of incoming TLS and invoke Envoy to process them. Envoy supports configuring private key providers and the private key provider (CryptoMB) was released in 1.20 contrib build (https://github.com/envoyproxy/envoy/pull/17826 ).

CryptoMB private key provider allows Envoy to handle the incoming TLS handshakes’ RSA operations with the help of AVX-512 multi-buffer instructions, which allow up to eight RSA or ECDSA operations to be gathered into a buffer and processed simultaneously. This helps increase the performance especially when there are a large number of incoming TLS requests. 

Intel has published a whitepaper that contains more information about the AVX-512 instructions and potential performance increase: https://www.intel.com/content/www/us/en/architecture-and-technology/crypto-acceleration-in-xeon-scalable-processors-wp.html.
You can also find a presentation here: https://www.intel.com/content/www/us/en/developer/videos/accelerate-envoy-with-advanced-vector-extensions.html

To use the CryptoMB private key providers, users can simply configure Envoy like:
```
 tls_certificates:
   certificate_chain: { "filename": "/path/cert.pem" }
   private_key_provider:
     provider_name: cryptomb
     typed_config:
       "@type": type.googleapis.com/envoy.extensions.private_key_providers.cryptomb.v3alpha.CryptoMbPrivateKeyMethodConfig
       private_key: { "filename": "/path/key.pem" }       
       poll_delay: 0.1s
```
# Proposal
I think Kourier also needs to support this feature.  As an ingress gateway, it should be capable of handling such a large number of TLS at the same time. 
We should:
1. make the envoy configuration configurable, instead of using a static YAML file. 
2. add a configure option in Kourier's ingress gateway and let it pass the private key provider info to Envoy's configuration. 

Please kindly leave your comments if any suggestions or questions.

**Comment by xxinran** [comment]
we have an discussion about how to add configuration here. #892

**Comment by nak3** [comment]
In addition to https://github.com/knative-sandbox/net-kourier/issues/892 one more question, do you think it is possible to test this feature on our CI?

**Comment by xxinran** [comment]
Currently, the TLS is supported by `Secret`. To make it more flexible and extensible, we can make it configurable via a new config map`config-tls` in `kourier-system` namespace.
The config map should be like:
```
kind: ConfigMap
metadata:
  name: config-tls
  namespace: kourier-system
data:
  privateKey: "/path/key_file"
  certificate: "/path/cert_file"
```
If users want to benefit from private key provider in Envoy, they can also configure the related private key provider in this config map, and related argments required by this provider, the config map should be like:
```
kind: ConfigMap
metadata:
  name: config-tls
  namespace: kourier-system
data:
  privateKey: "/path/key_file"
  certificate: "/path/cert_file"
  privateKeyProvider: |
     provider_name_xyz:
         argA: xxx
         argB: yyy  
```
